# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 04723968ecc71d4c3572492e342b9f9eb8e4c242c260291f10e2b1d70931647a6b5c131bba7d8a9d25ab90116eec46cb055ba0638b5c0deb510f857a50ff4641

test:
  secret_key_base: e64478d6323f27ef804919878c1aa2d27207ec0296145f0b191f268d37eb03962c4d3c3890350b3132aecd9e970ea7116dd546bf6930b71af2e4b54376a821d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
